In [2]:
type(10)

int

In [3]:
type(1.314)

float

In [5]:
type("hello")

str

In [4]:
# 定义列表：存储医学检测核心特征名
lab_features = ["Glucose", "BMI", "BloodPressure", "Age", "Insulin"]
# 定义列表：存储常见糖尿病并发症
complications = ["糖尿病肾病", "糖尿病视网膜病变", "周围神经病变"]
# 列表索引取值（索引从0开始，取第一个检测特征）
first_feature = lab_features[0]
# 负索引取值（取最后一个并发症）
last_complication = complications[-1]
print("首个检测特征：", first_feature)
print("最后一个并发症：", last_complication)
# 列表常用操作：添加医学指标、修改病症名称
lab_features.append("HbA1c")  # 末尾添加糖化血红蛋白指标
complications[1] = "糖尿病眼底病变"  # 修改索引1的并发症名称
print("添加指标后的特征列表：", lab_features)
print("修改后的并发症列表：", complications)


首个检测特征： Glucose
最后一个并发症： 周围神经病变
添加指标后的特征列表： ['Glucose', 'BMI', 'BloodPressure', 'Age', 'Insulin', 'HbA1c']
修改后的并发症列表： ['糖尿病肾病', '糖尿病眼底病变', '周围神经病变']


In [5]:
# 直接定义布尔值：标记检测结果是否异常
is_index_abnormal = True
is_patient_healthy = False

# 医学指标比较：判断血糖、血压是否超出正常范围
glucose = 165  # 血糖值(mg/dL)
bp = 95        # 舒张压(mmHg)
print("血糖高于正常阈值(140)：", glucose > 140)
print("舒张压等于正常阈值(80)：", bp == 80)
print("血糖不高于140：", not(glucose > 140))

# 逻辑运算组合：判断是否为高血糖合并高血压
is_diabetes_hypertension = (glucose > 140) and (bp > 90)
print("高血糖合并高血压：", is_diabetes_hypertension)

# 布尔值与数字转换：医学统计中量化判断结果
print("异常标记(True)转数字：", int(is_index_abnormal))
print("健康标记(False)转数字：", int(is_patient_healthy))

血糖高于正常阈值(140)： True
舒张压等于正常阈值(80)： False
血糖不高于140： False
高血糖合并高血压： True
异常标记(True)转数字： 1
健康标记(False)转数字： 0


In [7]:
# 整数和浮点数
age = 30  # 年龄（整数）
height = 1.75  # 身高（浮点数）

# 字符串
name = "John Doe"  # 患者姓名

# 布尔值
is_diabetic = True  # 患者是否为糖尿病患者

# 列表
symptoms = ['fatigue', 'thirst', 'urination']  # 患者症状列表

# 字典
patient_info = {'name': name, 'age': age, 'is_diabetic': is_diabetic}  # 患者信息


In [8]:
glucose_level = 150  # 假设血糖值为150

# 判断血糖是否超过正常范围
if glucose_level > 140:
    print("Blood sugar is high!")
else:
    print("Blood sugar is normal.")


Blood sugar is high!


In [10]:
# for循环：遍历患者症状列表
for symptom in symptoms:
    print(f"Symptom: {symptom}")

Symptom: fatigue
Symptom: thirst
Symptom: urination


In [11]:
# while循环：检查症状
counter = 0
while counter < 3:
    print(f"Checking symptom {counter + 1}")
    counter += 1

Checking symptom 1
Checking symptom 2
Checking symptom 3


In [ ]:
def function_name(parameter1, parameter2):
    """
    函数的文档字符串（可选），描述函数的功能、参数和返回值
    """
    # 执行的代码块
    return result


In [16]:
def calculate_bmi(weight, height):
    """
    计算体重指数（BMI）

    参数:
    weight (float): 体重（单位：kg）
    height (float): 身高（单位：m）

    返回:
    float: 计算得到的BMI值
    """
    bmi = weight / (height ** 2)
    return bmi

In [17]:
weight = 70  # 体重（kg）
height = 1.75  # 身高（m）

bmi = calculate_bmi(weight, height)  # 调用函数并获取BMI值
print(f"BMI: {bmi}")


BMI: 22.857142857142858


In [ ]:
def example_function():
    x = 5  # 使用4个空格进行缩进
    if x > 0:
        print("Positive number")

In [ ]:
# 长行需要换行
long_string = "This is a very long string that should be wrapped to fit within the 79 character limit."

# 使用反斜杠或括号将长行代码分成多个短行
result = long_function_name_with_long_parameters(
    parameter1, parameter2, parameter3, parameter4
)

In [ ]:
def func1():
    pass

def func2():
    pass  # 两个函数之间需要有两个空行

In [ ]:
# 合适的空格使用
x = 5
y = x + 2

In [ ]:
# 错误的空格使用
x = 5+2  # 不要这样写

In [ ]:
x = 5  # 这是一个示例变量

In [ ]:
def calculate_bmi(weight, height):
    """
    计算BMI（体重指数）
    
    参数:
    weight (float): 体重（单位：kg）
    height (float): 身高（单位：m）

    返回:
    float: 计算得到的BMI值
    """
    return weight / (height ** 2)


In [ ]:
class Patient:
    """
    一个表示患者的类
    
    属性:
    name (str): 患者的名字
    age (int): 患者的年龄
    is_diabetic (bool): 患者是否为糖尿病患者
    """
    def __init__(self, name, age, is_diabetic):
        self.name = name
        self.age = age
        self.is_diabetic = is_diabetic


In [ ]:
try:
    result = x / y
except ZeroDivisionError:
    print("Cannot divide by zero!")


In [ ]:
import logging

logging.basicConfig(level=logging.INFO)
logging.info("This is an info message")
logging.error("This is an error message")


In [ ]:
"""
This module contains functions for basic mathematical operations.
It includes functions to add, subtract, multiply, and divide numbers.
"""


In [ ]:
def calculate_bmi(weight, height):
    """
    计算体重指数（BMI）
    
    参数:
    weight (float): 体重（单位：kg）
    height (float): 身高（单位：m）
    
    返回:
    float: 计算得到的BMI值
    """
    return weight / (height ** 2)


In [7]:
import logging
import re
import pandas as pd

# --- 配置日志系统 ---
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler('medical_data_processing.log', encoding='utf-8'),
        logging.StreamHandler()
    ]
)

logger = logging.getLogger('DiabetesProcessor')

# 模拟一组存在问题的患者数据
problematic_patients = [
    {"id": "P001", "glucose": "150mg/dL"},  # 含单位字符串
    {"id": "P002", "glucose": None},       # 缺失值
    {"id": "P003", "glucose": -5},         # 生理异常值
    {"id": "P004", "glucose": 620}         # 极端异常值
]

def clean_glucose_value(raw_value):
    """
    清洗血糖数据：
    1. 去除单位
    2. 转换为 float
    3. 返回标准数值
    """
    if raw_value is None:
        return None

    if isinstance(raw_value, str):
        # 提取字符串中的数字部分（支持小数）
        match = re.search(r"[-+]?\d*\.?\d+", raw_value)
        if match:
            return float(match.group())
        else:
            raise ValueError("无法从字符串中提取数值")

    return float(raw_value)


for patient in problematic_patients:
    pid = patient.get("id", "Unknown")

    try:
        # 数据清洗
        glucose_value = clean_glucose_value(patient.get("glucose"))

        # 缺失值校验
        if pd.isna(glucose_value):
            raise ValueError("血糖值为缺失值（NaN）")

        # 生理逻辑校验
        if glucose_value < 0:
            raise ValueError(f"血糖值{glucose_value}不符合生理常识")

        # 医学合理范围校验（例如 0~600 mg/dL）
        if not (0 <= glucose_value <= 600):
            raise ValueError(f"血糖值{glucose_value}超出医学合理范围")

        logger.info(f"患者{pid}血糖值校验通过：{glucose_value} mg/dL")

    except ValueError as e:
        logger.warning(f"患者{pid}数据异常：{e}，已记录并跳过")

    except Exception as e:
        logger.critical(f"患者{pid}发生系统级错误：{e}")
        # 不再终止程序，而是继续处理下一个患者
        continue

2026-02-21 10:33:37,288 - DiabetesProcessor - INFO - 患者P001血糖值校验通过：150.0 mg/dL
2026-02-21 10:33:37,289 - DiabetesProcessor - WARNING - 患者P002数据异常：血糖值为缺失值（NaN），已记录并跳过
2026-02-21 10:33:37,290 - DiabetesProcessor - WARNING - 患者P003数据异常：血糖值-5.0不符合生理常识，已记录并跳过
2026-02-21 10:33:37,290 - DiabetesProcessor - WARNING - 患者P004数据异常：血糖值620.0超出医学合理范围，已记录并跳过


In [ ]:
# 打开文件（只读模式）
file = open('data.txt', 'r')  # 'r'表示只读模式

# 读取文件内容
content = file.read()  # 读取整个文件内容
print(content)

# 关闭文件
file.close()

# 打开文件（写入模式）
file = open('output.txt', 'w')  # 'w'表示写入模式，如果文件不存在，会自动创建文件

# 写入内容
file.write("Hello, this is a test message.\n")
file.write("This is the second line.")

# 关闭文件
file.close()

# 使用with语句打开文件进行读取
with open('data.txt', 'r') as file:
    content = file.read()
    print(content)

# 使用readline逐行读取文件
with open('data.txt', 'r') as file:
    line = file.readline()
    while line:
        print(line.strip())  # 使用strip()去掉行末的换行符
        line = file.readline()

# 使用readlines读取文件所有行，并返回一个列表
with open('data.txt', 'r') as file:
    lines = file.readlines()
    for line in lines:
        print(line.strip())

import pandas as pd

# 读取CSV文件
df = pd.read_csv('patients.csv')

# 查看前五行数据
print(df.head())


# 读取Excel文件
df = pd.read_excel('patients.xlsx', sheet_name='Sheet1')

# 查看前五行数据
print(df.head())

# 将DataFrame保存为CSV文件
df.to_csv('cleaned_patients.csv', index=False)

# 将DataFrame保存为Excel文件
df.to_excel('cleaned_patients.xlsx', index=False)



In [19]:
import numpy as np

# 创建一个一维数组
arr = np.array([1, 2, 3, 4, 5])
print(arr)

# 创建一个二维数组
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [20]:
# 向量化加法
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result = arr1 + arr2  # 对两个数组进行加法
print(result)  


[5 7 9]


In [21]:
# 数组的标量运算
arr = np.array([1, 2, 3, 4, 5])

# 每个元素乘以2
arr2 = arr * 2
print(arr2) 

# 每个元素平方
arr3 = arr ** 2
print(arr3)  


[ 2  4  6  8 10]
[ 1  4  9 16 25]


In [28]:
arr = np.array([1, 2, 3, 4, 5])

# 计算均值
mean = np.mean(arr)
print(f"Mean: {mean}")

# 计算标准差
std_dev = np.std(arr)
print(f"Standard Deviation: {std_dev}")


Mean: 3.0
Standard Deviation: 1.4142135623730951


In [23]:
import pandas as pd

# 通过字典创建DataFrame
data = {
    'Name': ['John', 'Alice', 'Bob'],
    'Age': [25, 30, 22],
    'Height': [175, 160, 180]
}

df = pd.DataFrame(data)
print(df)


    Name  Age  Height
0   John   25     175
1  Alice   30     160
2    Bob   22     180


In [25]:
# 选择某一列
age_column = df['Age']
print(age_column)


0    25
1    30
2    22
Name: Age, dtype: int64


In [26]:
# 选择某一行
first_row = df.iloc[0]
print(first_row)


Name      John
Age         25
Height     175
Name: 0, dtype: object


In [27]:

# 选择特定的行和列
subset = df.loc[0:1, ['Name', 'Age']]
print(subset)

    Name  Age
0   John   25
1  Alice   30
